dpkg-deb -Zgzip -b bubble-mania
dpkg-deb -Zgzip -b fireflies
dpkg-deb -Zgzip -b floaty-squares
dpkg-deb -Zgzip -b gradient-mania
dpkg-deb -Zgzip -b misty
dpkg-deb -Zgzip -b mosaic
dpkg-deb -Zgzip -b radial-widget
dpkg-deb -Zgzip -b smooth-bar
dpkg-deb -Zgzip -b solar-system
dpkg-deb -Zgzip -b stars